// The recovery certificate, offered inside the ceremony.
//
// The thing being guarded is not that a screen renders. It is that the step
// asks for NOTHING: the phrase was generated by the previous step and is in
// hand, so there is no field to mistype and no paste to go wrong. That is the
// whole reason this moved out of the post-onboarding sheet, and a refactor
// that quietly put a text field back would restore the defect it was built to
// remove.

import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:xveil/core/ids.dart';
import 'package:xveil/features/onboarding/recovery_certificate_step.dart';
import 'package:xveil/l10n/app_localizations.dart';
import 'package:xveil/l10n/app_localizations_en.dart';

const _phrase =
    'abandon ability able about above absent absorb abstract absurd abuse '
    'access accident account accuse achieve acid acoustic acquire across '
    'act action actor actress actual';

MintedRecovery _fakeMint(String phrase) => MintedRecovery(
  credential: Uint8List.fromList([1, 2, 3]),
  certificate: 'xveil-recovery:v1:$phrase',
  code: 'xvrc-TESTCODE_Aa09',
  nodeId: NodeId.fromHex('ab' * 32),
);

Widget _host({
  required void Function({required bool saved, Uint8List? credential}) onDone,
  MintedRecovery Function(String)? mint,
}) => MaterialApp(
  locale: const Locale('en'),
  localizationsDelegates: AppL10n.localizationsDelegates,
  supportedLocales: AppL10n.supportedLocales,
  home: Scaffold(
    body: RecoveryCertificateStep(
      phrase: _phrase,
      onDone: onDone,
      mint: mint ?? _fakeMint,
    ),
  ),
);

void main() {
  testWidgets('the step never asks for the phrase back', (tester) async {
    await tester.pumpWidget(_host(onDone: ({required saved, credential}) {}));
    await tester.pumpAndSettle();

    // Before minting.
    expect(
      find.byType(TextField),
      findsNothing,
      reason: 'the phrase is in hand; a field here is the defect returning',
    );

    await tester.tap(find.byIcon(Icons.verified_user_outlined));
    await tester.pumpAndSettle();

    // And after: the certificate and the code are shown, still nothing typed.
    expect(find.byType(TextField), findsNothing);
  });

  testWidgets('it says where to go when the offer is declined', (tester) async {
    await tester.pumpWidget(_host(onDone: ({required saved, credential}) {}));
    await tester.pumpAndSettle();
    final l = AppL10nEn();
    // The instruction is on screen BEFORE the decline, not after it: someone
    // who taps "not now" is gone, and a sentence shown to a screen they have
    // already left is a sentence nobody reads.
    expect(find.text(l.onboardCertLater), findsOneWidget);
    expect(find.text(l.onboardCertSkip), findsOneWidget);
  });

  testWidgets('declining reports that nothing was saved', (tester) async {
    bool? seen;
    await tester.pumpWidget(
      _host(onDone: ({required bool saved, Uint8List? credential}) => seen = saved),
    );
    await tester.pumpAndSettle();
    await tester.tap(find.text(AppL10nEn().onboardCertSkip));
    await tester.pumpAndSettle();
    expect(
      seen,
      isFalse,
      reason: 'a decline must leave the standing reminder up',
    );
  });

  testWidgets('leaving with an unsaved certificate is questioned once', (
    tester,
  ) async {
    var done = 0;
    await tester.pumpWidget(_host(onDone: ({required saved, credential}) => done++));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.verified_user_outlined));
    await tester.pumpAndSettle();

    final l = AppL10nEn();
    // The step is longer than the test window; a tap on a widget below the
    // fold hits the viewport, not the button, and the assertion that follows
    // then passes for the wrong reason.
    Future<void> pressContinue() async {
      final button = find.text(l.onboardCertContinue);
      await tester.ensureVisible(button);
      await tester.pumpAndSettle();
      await tester.tap(button);
      await tester.pumpAndSettle();
    }

    await pressContinue();
    expect(done, 0, reason: 'the pair exists only on this screen');
    expect(find.text(l.onboardCertNotSavedYet), findsOneWidget);

    // ...and only once. It is their identity and their decision.
    await pressContinue();
    expect(done, 1);
  });

  testWidgets('a mint that throws says so instead of hanging', (tester) async {
    await tester.pumpWidget(
      _host(
        onDone: ({required saved, credential}) {},
        mint: (_) => throw StateError('no native library here'),
      ),
    );
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.verified_user_outlined));
    await tester.pumpAndSettle();
    expect(find.text(AppL10nEn().onboardCertFailed), findsOneWidget);
    // The offer stays takeable: a failure here must not strand the ceremony.
    expect(find.text(AppL10nEn().onboardCertSkip), findsOneWidget);
  });
}
