import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// The Windows runner must not hand a message to a controller it is destroying.
///
/// `windowManager.destroy()` — the tray's Quit, and the close button when
/// close-to-tray is off — is `PostQuitMessage(0)` on Windows and nothing more.
/// The top-level window is therefore still alive when the message loop
/// returns, `FlutterWindow::OnDestroy` never runs, and `~FlutterWindow` is
/// where the controller finally dies. Destroying it destroys the engine's
/// child view window, and `DestroyWindow` dispatches messages back into
/// `MessageHandler` while the controller is half-gone.
///
/// `std::unique_ptr`'s destructor does not clear the pointer before running
/// the deleter, so `if (flutter_controller_)` was true and the message reached
/// a destroyed object: an access violation at `ldr x0,[x0,#0x10]` with x0 = 0.
/// Escaping a kernel user-callback makes that
/// STATUS_FATAL_USER_CALLBACK_EXCEPTION, and Windows Error Reporting then held
/// the process about 150 seconds — the "Quit hangs" report.
///
/// These files are GENERATED by `flutter create` and are routinely refreshed
/// wholesale when the template moves. The fix lives in one of them, so a
/// refresh silently reintroduces a crash that only shows on the way out. That
/// is what this guard is for.
void main() {
  late String source;

  setUpAll(() {
    final file = File('windows/runner/flutter_window.cpp');
    if (!file.existsSync()) {
      fail(
        'windows/runner/flutter_window.cpp is missing, so this guard cannot '
        'check the file it exists to check — re-aim it, do not delete it',
      );
    }
    source = file.readAsStringSync();
  });

  /// Everything between [from] and the first `\n}` at column 0 after it.
  String body(String from) {
    final start = source.indexOf(from);
    expect(
      start,
      isNot(-1),
      reason: '$from moved or was renamed; re-aim this guard',
    );
    final rest = source.substring(start);
    final end = rest.indexOf('\n}');
    expect(end, isNot(-1), reason: '$from has no closing brace at column 0');
    return rest.substring(0, end);
  }

  test('the destructor clears the controller before destroying it', () {
    final destructor = body('FlutterWindow::~FlutterWindow()');
    expect(
      destructor.contains('std::move(flutter_controller_)'),
      isTrue,
      reason:
          '~FlutterWindow must move the controller out, which leaves the '
          'member null while the deleter runs. Destroying it in place leaves '
          'the pointer set, MessageHandler passes its guard, and the '
          're-entrant message from DestroyWindow hits a destroyed controller.',
    );
    expect(
      destructor.replaceAll(RegExp(r'//[^\n]*'), '').trim(),
      isNot(''),
      reason:
          'the destructor went back to being empty, which is the template '
          'shape that crashes on quit',
    );
  });

  test('the font-change branch does not dereference a null controller', () {
    final handler = body('FlutterWindow::MessageHandler');
    final fontBranch = handler.substring(handler.indexOf('WM_FONTCHANGE'));
    expect(
      fontBranch.contains('if (flutter_controller_)'),
      isTrue,
      reason:
          'WM_FONTCHANGE dereferences flutter_controller_; a message can now '
          'reach MessageHandler with no controller, which is the point of the '
          'destructor change',
    );
  });

  /// Vacuity: the guard above is only meaningful while MessageHandler really
  /// does forward to the controller. If that call goes away the re-entrancy
  /// cannot happen and both assertions would pass over nothing.
  test('the message handler still forwards to the controller', () {
    expect(
      body(
        'FlutterWindow::MessageHandler',
      ).contains('flutter_controller_->HandleTopLevelWindowProc'),
      isTrue,
      reason:
          'MessageHandler no longer forwards top-level messages; the crash '
          'this guards cannot occur, so re-aim or retire it deliberately',
    );
  });
}
