import 'dart:io';
import 'dart:ui' show PlatformDispatcher;

import 'package:flutter/foundation.dart' show listEquals;
import 'package:flutter/widgets.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:tray_manager/tray_manager.dart';
import 'package:window_manager/window_manager.dart';

import '../core/log.dart';
import '../domain/chat.dart' show Conversation;
import '../domain/chat_folder.dart' show folderUnreadCount, unreadBadgeText;
import '../l10n/app_localizations.dart';
import '../state/app_controller.dart';
import '../state/close_to_tray_controller.dart';
import '../state/messaging.dart' show conversationsProvider;

/// True on the three desktop platforms that have a window + a system tray.
bool get isDesktopTrayPlatform =>
    Platform.isMacOS || Platform.isLinux || Platform.isWindows;

/// One-time desktop window init, called from `main` BEFORE `runApp` (no-op off
/// desktop). Arms window_manager so [DesktopTrayHost] can intercept the close
/// button and hide to tray instead of quitting.
Future<void> initDesktopWindow() async {
  if (!isDesktopTrayPlatform) return;
  await windowManager.ensureInitialized();
  // Intercept the close button; the host's onWindowClose decides hide-vs-quit
  // based on the persisted setting.
  await windowManager.setPreventClose(true);
}

const kTrayShowKey = 'show';
const kTrayHideKey = 'hide';
const kTrayLockKey = 'lock';
const kTrayQuitKey = 'quit';
const kTrayUnreadKey = 'unread';
const kTrayIdentityKeyPrefix = 'identity:';

/// Tray hover tooltip: the active identity's name while unlocked, else the app
/// name. Pure — unit-tested.
String trayTooltip(AppState app) {
  final id = app.activeIdentity;
  if (app.phase == AppPhase.ready && id != null && id.isNotEmpty) return id;
  return 'xVeil';
}

/// The tray context menu for [app]. Pure (no tray/plugin calls) so the
/// platform-independent shape is unit-testable: identity switching appears
/// only for an unlocked master with something to switch to, lock only while
/// a space is actually open. [unread] > 0 adds a disabled count line on top.
Menu buildTrayMenu(AppL10n l, AppState app, {int unread = 0}) {
  final ready = app.phase == AppPhase.ready;
  final items = <MenuItem>[];
  if (unread > 0) {
    items
      ..add(
        MenuItem(
          key: kTrayUnreadKey,
          label: l.trayUnread(unreadBadgeText(unread)),
          disabled: true,
        ),
      )
      ..add(MenuItem.separator());
  }
  items
    ..add(MenuItem(key: kTrayShowKey, label: l.trayShow))
    ..add(MenuItem(key: kTrayHideKey, label: l.trayHide));
  if (ready && app.identities.length > 1) {
    items
      ..add(MenuItem.separator())
      ..add(
        MenuItem.submenu(
          label: l.trayIdentities,
          submenu: Menu(
            items: [
              for (final label in app.identities)
                MenuItem.checkbox(
                  key: '$kTrayIdentityKeyPrefix$label',
                  label: label,
                  checked: label == app.activeIdentity,
                ),
            ],
          ),
        ),
      );
  }
  if (ready || app.phase == AppPhase.pickingIdentity) {
    items
      ..add(MenuItem.separator())
      ..add(MenuItem(key: kTrayLockKey, label: l.trayLock));
  }
  items
    ..add(MenuItem.separator())
    ..add(MenuItem(key: kTrayQuitKey, label: l.trayQuit));
  return Menu(items: items);
}

/// Wraps the app on desktop to own the tray icon + menu and the
/// close-to-tray behavior. Transparent passthrough on mobile.
///
/// Behavior:
/// * Close button → hide to tray (when [closeToTrayProvider] is on) so the
///   embedded node keeps running and notifications keep arriving; else quit.
/// * Tray icon click → show + focus the window.
/// * Tray menu → Show / Hide / switch identity / Lock / Quit, rebuilt as the
///   app state changes (lock/unlock, identity switch, roster edits).
class DesktopTrayHost extends ConsumerStatefulWidget {
  const DesktopTrayHost({super.key, required this.child});
  final Widget child;

  @override
  ConsumerState<DesktopTrayHost> createState() => _DesktopTrayHostState();
}

class _DesktopTrayHostState extends ConsumerState<DesktopTrayHost>
    with WindowListener, TrayListener {
  bool get _enabled => isDesktopTrayPlatform;

  @override
  void initState() {
    super.initState();
    if (!_enabled) return;
    windowManager.addListener(this);
    trayManager.addListener(this);
    WidgetsBinding.instance.addPostFrameCallback((_) => _initTray());
  }

  Future<void> _initTray() async {
    if (!mounted) return;
    try {
      // Re-arm close interception from a live frame too: the pre-runApp call
      // in initDesktopWindow is the designed path, but re-asserting here makes
      // close-to-tray survive any init-order regression.
      await windowManager.setPreventClose(true);
      // Transparent tray art, generated by tool/make_tray_icon.py from
      // assets/icon/tray_icon_source.png. Windows' LoadImage wants a real
      // .ico; macOS/Linux take the PNG (macOS scales it to its 18pt slot).
      await trayManager.setIcon(
        Platform.isWindows
            ? 'assets/icon/tray_icon.ico'
            : 'assets/icon/tray_icon.png',
      );
      await _refreshMenu();
      final armed = await windowManager.isPreventClose();
      devLog(() => 'xVeil[tray]: icon+menu installed (preventClose=$armed)');
    } catch (e) {
      // A tray init failure (no tray available, headless CI) must never crash
      // the app — the window just behaves normally. LOUD in the log: a silent
      // catch here previously hid the l10n crash entirely.
      devLog(() => 'xVeil[tray]: init FAILED: $e');
    }
  }

  /// (Re)installs the context menu for the current app state. Menu labels use
  /// the OS locale: this host sits ABOVE MaterialApp (no Localizations in
  /// scope), so AppL10n.of(context) here would throw and kill tray init.
  Future<void> _refreshMenu() async {
    if (!mounted) return;
    final l = lookupAppL10n(PlatformDispatcher.instance.locale);
    final app = ref.read(appControllerProvider);
    _lastUnread = _totalUnread();
    try {
      await trayManager.setContextMenu(buildTrayMenu(l, app, unread: _lastUnread));
      await trayManager.setToolTip(trayTooltip(app));
    } catch (e) {
      devLog(() => 'xVeil[tray]: menu refresh FAILED: $e');
    }
  }

  /// Total unread across all conversations (0 when the roster stream has no
  /// value yet, e.g. while locked).
  int _totalUnread() => folderUnreadCount(
        ref.read(conversationsProvider).valueOrNull ?? const <Conversation>[],
        null,
      );

  // Last unread total pushed to the tray — the roster stream ticks often, so
  // the menu is only rebuilt when this actually changes.
  int _lastUnread = 0;

  @override
  void dispose() {
    if (_enabled) {
      windowManager.removeListener(this);
      trayManager.removeListener(this);
    }
    super.dispose();
  }

  /// Serializes + debounces window restores. A tray-icon DOUBLE-click fires
  /// two mouse-down events back-to-back; two overlapping native show()/focus()
  /// calls crashed the app on macOS (device-observed), so drop any request
  /// that arrives while one is in flight or within the debounce window.
  bool _showInFlight = false;
  DateTime _lastShowAt = DateTime.fromMillisecondsSinceEpoch(0);

  Future<void> _show() async {
    final now = DateTime.now();
    if (_showInFlight ||
        now.difference(_lastShowAt) < const Duration(milliseconds: 400)) {
      return;
    }
    _showInFlight = true;
    _lastShowAt = now;
    try {
      await windowManager.show();
      await windowManager.focus();
    } catch (e) {
      devLog(() => 'xVeil[tray]: show/focus FAILED: $e');
    } finally {
      _showInFlight = false;
    }
  }

  // ── WindowListener ────────────────────────────────────────────────────────
  @override
  void onWindowClose() async {
    // preventClose is armed (initDesktopWindow), so the window won't close on
    // its own — we decide. Close-to-tray on → hide; off → really quit.
    final closeToTray = ref.read(closeToTrayProvider);
    devLog(() => 'xVeil[tray]: window close intercepted, '
        'closeToTray=$closeToTray');
    if (closeToTray) {
      await windowManager.hide();
    } else {
      await windowManager.setPreventClose(false);
      await windowManager.destroy();
    }
  }

  // ── TrayListener ──────────────────────────────────────────────────────────
  @override
  void onTrayIconMouseDown() => _show();

  @override
  void onTrayIconRightMouseDown() => trayManager.popUpContextMenu();

  @override
  void onTrayMenuItemClick(MenuItem menuItem) async {
    final key = menuItem.key;
    if (key == null) return;
    if (key.startsWith(kTrayIdentityKeyPrefix)) {
      final label = key.substring(kTrayIdentityKeyPrefix.length);
      devLog(() => 'xVeil[tray]: switch identity -> $label');
      await ref.read(appControllerProvider.notifier).switchIdentity(label);
      return;
    }
    switch (key) {
      case kTrayShowKey:
        await _show();
      case kTrayHideKey:
        await windowManager.hide();
      case kTrayLockKey:
        devLog(() => 'xVeil[tray]: lock');
        await ref.read(appControllerProvider.notifier).lock();
      case kTrayQuitKey:
        await windowManager.setPreventClose(false);
        await windowManager.destroy();
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_enabled) {
      // Rebuild the menu when anything it renders changes: lock/unlock,
      // identity switch, or roster edits (add/rename/delete identity).
      ref.listen(appControllerProvider, (prev, next) {
        if (prev?.phase != next.phase ||
            prev?.activeIdentity != next.activeIdentity ||
            !listEquals(prev?.identities, next.identities)) {
          _refreshMenu();
        }
      });
      // Unread total also drives the menu's count line — refresh only when it
      // changes, since the roster stream emits far more often than the count
      // moves.
      ref.listen(conversationsProvider, (_, next) {
        final now = folderUnreadCount(
          next.valueOrNull ?? const <Conversation>[],
          null,
        );
        if (now != _lastUnread) _refreshMenu();
      });
    }
    return widget.child;
  }
}
