// Curated emoji dataset for the composer picker (user remark #2,
// 2026-07-10): grouped like the standard keyboards, each entry carrying an
// english search name. Deliberately a HAND-SIZED subset (~400) — v1 needs a
// fast, dependency-free picker, not the full 3.6K Unicode registry; the
// dataset is trivially extendable. Entries are `emoji|name` to keep the
// source compact; parsed once into [emojiGroups].

/// One picker group: a label key (l10n happens at the widget), an icon-ish
/// title emoji for the tab, and the entries.
class EmojiGroup {
  const EmojiGroup(this.name, this.tab, this.entries);
  final String name; // stable key, also the tab tooltip (english)
  final String tab; // the emoji shown on the group tab
  final List<EmojiEntry> entries;
}

class EmojiEntry {
  const EmojiEntry(this.char, this.name);
  final String char;
  final String name;
}

List<EmojiEntry> _parse(List<String> raw) => [
      for (final r in raw)
        EmojiEntry(r.substring(0, r.indexOf('|')),
            r.substring(r.indexOf('|') + 1)),
    ];

final List<EmojiGroup> emojiGroups = [
  EmojiGroup('Smileys', '😀', _parse(const [
    '😀|grinning', '😃|smiley', '😄|smile', '😁|grin', '😆|laughing',
    '😅|sweat smile', '🤣|rofl', '😂|joy tears', '🙂|slight smile',
    '😉|wink', '😊|blush', '😇|innocent', '🥰|hearts face', '😍|heart eyes',
    '🤩|star struck', '😘|kiss', '😗|kissing', '☺️|relaxed', '😚|kiss closed',
    '😋|yum', '😛|tongue', '😜|wink tongue', '🤪|zany', '😝|squint tongue',
    '🤑|money face', '🤗|hug', '🤭|hand over mouth', '🤫|shush', '🤔|thinking',
    '🤐|zipper', '🤨|raised eyebrow', '😐|neutral', '😑|expressionless',
    '😶|no mouth', '😏|smirk', '😒|unamused', '🙄|eye roll', '😬|grimace',
    '🤥|lying', '😌|relieved', '😔|pensive', '😪|sleepy', '🤤|drooling',
    '😴|sleeping', '😷|mask', '🤒|thermometer', '🤕|bandage', '🤢|nauseated',
    '🤮|vomit', '🤧|sneeze', '🥵|hot', '🥶|cold', '🥴|woozy', '😵|dizzy',
    '🤯|mind blown', '🤠|cowboy', '🥳|party', '😎|sunglasses', '🤓|nerd',
    '🧐|monocle', '😕|confused', '😟|worried', '🙁|frown', '☹️|big frown',
    '😮|open mouth', '😯|hushed', '😲|astonished', '😳|flushed', '🥺|pleading',
    '😦|frowning open', '😧|anguished', '😨|fearful', '😰|anxious sweat',
    '😥|sad relieved', '😢|cry', '😭|sob', '😱|scream', '😖|confounded',
    '😣|persevere', '😞|disappointed', '😓|downcast sweat', '😩|weary',
    '😫|tired', '🥱|yawn', '😤|triumph steam', '😡|rage', '😠|angry',
    '🤬|cursing', '😈|smiling devil', '👿|angry devil', '💀|skull',
    '☠️|crossbones', '💩|poop', '🤡|clown', '👹|ogre', '👺|goblin',
    '👻|ghost', '👽|alien', '🤖|robot', '😺|cat smile', '😸|cat grin',
    '😹|cat joy', '😻|cat heart eyes', '😼|cat smirk', '😽|cat kiss',
    '🙀|cat scream', '😿|cat cry', '😾|cat pout',
  ])),
  EmojiGroup('People', '👋', _parse(const [
    '👋|wave', '🤚|raised back hand', '🖐️|splayed hand', '✋|raised hand',
    '🖖|vulcan', '👌|ok', '🤌|pinched fingers', '🤏|pinch', '✌️|victory',
    '🤞|crossed fingers', '🤟|love you', '🤘|rock on', '🤙|call me',
    '👈|point left', '👉|point right', '👆|point up', '👇|point down',
    '☝️|index up', '👍|thumbs up', '👎|thumbs down', '✊|fist', '👊|punch',
    '🤛|left fist', '🤜|right fist', '👏|clap', '🙌|raised hands',
    '👐|open hands', '🤲|palms up', '🤝|handshake', '🙏|pray thanks',
    '✍️|writing', '💅|nail polish', '🤳|selfie', '💪|muscle', '🦾|mech arm',
    '👂|ear', '👃|nose', '🧠|brain', '👀|eyes', '👁️|eye', '👄|mouth',
    '🫦|biting lip', '👶|baby', '🧒|child', '👦|boy', '👧|girl', '🧑|person',
    '👨|man', '👩|woman', '🧓|older person', '👴|old man', '👵|old woman',
    '🙍|frowning person', '🙎|pouting person', '🙅|no gesture',
    '🙆|ok gesture', '💁|tipping hand', '🙋|raising hand', '🧏|deaf person',
    '🙇|bow', '🤦|facepalm', '🤷|shrug', '👮|police', '🕵️|detective',
    '💂|guard', '👷|construction worker', '🤴|prince', '👸|princess',
    '👳|turban', '🤵|tuxedo', '👰|veil bride', '🤰|pregnant', '🤱|nursing',
    '👼|angel baby', '🎅|santa', '🤶|mrs claus', '🦸|superhero',
    '🦹|supervillain', '🧙|mage', '🧚|fairy', '🧛|vampire', '🧜|merperson',
    '🧝|elf', '🧞|genie', '🧟|zombie', '💃|dancer', '🕺|man dancing',
    '👯|bunny dancers', '🧍|standing', '🧎|kneeling', '🏃|runner',
    '🚶|walking', '👫|couple', '💑|couple heart', '👪|family',
  ])),
  EmojiGroup('Nature', '🐶', _parse(const [
    '🐶|dog', '🐱|cat', '🐭|mouse', '🐹|hamster', '🐰|rabbit', '🦊|fox',
    '🐻|bear', '🐼|panda', '🐨|koala', '🐯|tiger', '🦁|lion', '🐮|cow',
    '🐷|pig', '🐽|pig nose', '🐸|frog', '🐵|monkey', '🙈|see no evil',
    '🙉|hear no evil', '🙊|speak no evil', '🐒|monkey body', '🐔|chicken',
    '🐧|penguin', '🐦|bird', '🐤|chick', '🦆|duck', '🦅|eagle', '🦉|owl',
    '🦇|bat', '🐺|wolf', '🐗|boar', '🐴|horse', '🦄|unicorn', '🐝|bee',
    '🪲|beetle', '🦋|butterfly', '🐌|snail', '🐞|ladybug', '🐜|ant',
    '🕷️|spider', '🦂|scorpion', '🐢|turtle', '🐍|snake', '🦎|lizard',
    '🦖|t-rex', '🦕|dinosaur', '🐙|octopus', '🦑|squid', '🦐|shrimp',
    '🦀|crab', '🐡|blowfish', '🐠|tropical fish', '🐟|fish', '🐬|dolphin',
    '🐳|whale', '🦈|shark', '🐊|crocodile', '🐅|tiger body', '🐘|elephant',
    '🦒|giraffe', '🦘|kangaroo', '🐪|camel', '🦙|llama', '🐐|goat',
    '🐑|sheep', '🐎|racing horse', '🦌|deer', '🐕|dog body', '🐈|cat body',
    '🐾|paw prints', '🌵|cactus', '🎄|christmas tree', '🌲|evergreen',
    '🌳|tree', '🌴|palm', '🌱|seedling', '🌿|herb', '☘️|shamrock',
    '🍀|four leaf clover', '🍁|maple leaf', '🍂|fallen leaves', '🍃|wind leaves',
    '🌸|cherry blossom', '🌼|blossom', '🌻|sunflower', '🌺|hibiscus',
    '🌹|rose', '🥀|wilted', '🌷|tulip', '💐|bouquet', '🌞|sun face',
    '🌝|full moon face', '🌚|new moon face', '🌙|crescent', '⭐|star',
    '🌟|glowing star', '✨|sparkles', '⚡|lightning', '🔥|fire',
    '🌈|rainbow', '☀️|sun', '⛅|partly cloudy', '☁️|cloud', '🌧️|rain',
    '⛈️|storm', '❄️|snowflake', '⛄|snowman', '🌊|wave water', '💧|droplet',
  ])),
  EmojiGroup('Food', '🍏', _parse(const [
    '🍏|green apple', '🍎|apple', '🍐|pear', '🍊|tangerine', '🍋|lemon',
    '🍌|banana', '🍉|watermelon', '🍇|grapes', '🍓|strawberry',
    '🫐|blueberries', '🍈|melon', '🍒|cherries', '🍑|peach', '🥭|mango',
    '🍍|pineapple', '🥥|coconut', '🥝|kiwi', '🍅|tomato', '🍆|eggplant',
    '🥑|avocado', '🥦|broccoli', '🥬|leafy green', '🥒|cucumber',
    '🌶️|hot pepper', '🌽|corn', '🥕|carrot', '🧄|garlic', '🧅|onion',
    '🥔|potato', '🍠|sweet potato', '🥐|croissant', '🥯|bagel', '🍞|bread',
    '🥖|baguette', '🥨|pretzel', '🧀|cheese', '🥚|egg', '🍳|fried egg',
    '🧈|butter', '🥞|pancakes', '🧇|waffle', '🥓|bacon', '🥩|steak',
    '🍗|poultry leg', '🍖|meat on bone', '🌭|hot dog', '🍔|burger',
    '🍟|fries', '🍕|pizza', '🥪|sandwich', '🌮|taco', '🌯|burrito',
    '🥙|stuffed flatbread', '🧆|falafel', '🥘|paella', '🍝|spaghetti',
    '🍜|ramen', '🍲|stew', '🍛|curry', '🍣|sushi', '🍱|bento', '🥟|dumpling',
    '🍤|fried shrimp', '🍙|rice ball', '🍚|rice', '🍘|rice cracker',
    '🍥|fish cake', '🥮|moon cake', '🍢|oden', '🍡|dango', '🍧|shaved ice',
    '🍨|ice cream', '🍦|soft serve', '🥧|pie', '🧁|cupcake', '🍰|cake',
    '🎂|birthday cake', '🍮|custard', '🍭|lollipop', '🍬|candy',
    '🍫|chocolate', '🍿|popcorn', '🍩|donut', '🍪|cookie', '🌰|chestnut',
    '🥜|peanuts', '🍯|honey', '🥛|milk', '☕|coffee', '🍵|tea', '🧃|juice box',
    '🥤|cup with straw', '🍶|sake', '🍺|beer', '🍻|beers', '🥂|clink',
    '🍷|wine', '🥃|whisky', '🍸|cocktail', '🍹|tropical drink', '🧊|ice',
  ])),
  EmojiGroup('Activity', '⚽', _parse(const [
    '⚽|soccer', '🏀|basketball', '🏈|football', '⚾|baseball', '🥎|softball',
    '🎾|tennis', '🏐|volleyball', '🏉|rugby', '🥏|frisbee', '🎱|8 ball',
    '🪀|yo-yo', '🏓|ping pong', '🏸|badminton', '🏒|hockey', '🥍|lacrosse',
    '🏏|cricket', '🥅|goal', '⛳|golf', '🪁|kite', '🏹|archery',
    '🎣|fishing', '🤿|diving', '🥊|boxing', '🥋|martial arts', '🎽|shirt run',
    '🛹|skateboard', '🛼|roller skate', '🛷|sled', '⛸️|ice skate',
    '🥌|curling', '🎿|ski', '⛷️|skier', '🏂|snowboard', '🏋️|weights',
    '🤸|cartwheel', '🤼|wrestling', '🤽|water polo', '🤾|handball',
    '🧗|climbing', '🚴|cycling', '🚵|mountain bike', '🏇|horse racing',
    '🧘|lotus', '🏄|surfing', '🏊|swimming', '🤺|fencing', '🏆|trophy',
    '🥇|gold medal', '🥈|silver medal', '🥉|bronze medal', '🏅|medal',
    '🎖️|military medal', '🎗️|ribbon', '🎫|ticket', '🎟️|admission',
    '🎪|circus', '🤹|juggling', '🎭|theater', '🩰|ballet', '🎨|palette',
    '🎬|clapper', '🎤|microphone', '🎧|headphones', '🎼|score', '🎹|piano',
    '🥁|drum', '🎷|sax', '🎺|trumpet', '🎸|guitar', '🪕|banjo', '🎻|violin',
    '🎲|dice', '♟️|chess pawn', '🎯|dart', '🎳|bowling', '🎮|game controller',
    '🕹️|joystick', '🎰|slot machine', '🧩|puzzle',
  ])),
  EmojiGroup('Travel', '🚗', _parse(const [
    '🚗|car', '🚕|taxi', '🚙|suv', '🚌|bus', '🚎|trolleybus', '🏎️|race car',
    '🚓|police car', '🚑|ambulance', '🚒|fire engine', '🚐|minibus',
    '🛻|pickup', '🚚|truck', '🚛|semi', '🚜|tractor', '🦽|wheelchair',
    '🛴|kick scooter', '🚲|bicycle', '🛵|scooter', '🏍️|motorcycle',
    '🚨|police light', '🚔|oncoming police', '🚍|oncoming bus', '🚘|oncoming car',
    '🚖|oncoming taxi', '✈️|airplane', '🛫|takeoff', '🛬|landing',
    '🪂|parachute', '💺|seat', '🛰️|satellite', '🚀|rocket', '🛸|ufo',
    '🚁|helicopter', '🛶|canoe', '⛵|sailboat', '🚤|speedboat', '🛳️|cruise',
    '⛴️|ferry', '🚢|ship', '⚓|anchor', '🚧|construction', '⛽|fuel',
    '🚏|bus stop', '🚦|traffic light', '🚥|horizontal light', '🗺️|map',
    '🗿|moai', '🗽|liberty', '🗼|tokyo tower', '🏰|castle', '🏯|japanese castle',
    '🏟️|stadium', '🎡|ferris wheel', '🎢|roller coaster', '🎠|carousel',
    '⛲|fountain', '⛱️|umbrella beach', '🏖️|beach', '🏝️|island',
    '🏜️|desert', '🌋|volcano', '⛰️|mountain', '🏔️|snow mountain',
    '🗻|fuji', '🏕️|camping', '⛺|tent', '🏠|house', '🏡|house garden',
    '🏢|office', '🏥|hospital', '🏦|bank', '🏨|hotel', '🏪|convenience store',
    '🏫|school', '🏛️|classical building', '⛪|church', '🕌|mosque',
    '🕍|synagogue', '⛩️|shrine', '🌁|foggy', '🌃|night stars',
    '🌆|dusk city', '🌇|sunset city', '🌉|bridge night', '🌌|milky way',
  ])),
  EmojiGroup('Objects', '💡', _parse(const [
    '⌚|watch', '📱|phone', '💻|laptop', '⌨️|keyboard', '🖥️|desktop',
    '🖨️|printer', '🖱️|mouse device', '💽|minidisc', '💾|floppy', '💿|cd',
    '📀|dvd', '📷|camera', '📸|camera flash', '📹|camcorder', '🎥|movie camera',
    '📞|receiver', '☎️|telephone', '📟|pager', '📠|fax', '📺|tv',
    '📻|radio', '🎙️|studio mic', '⏰|alarm clock', '⏱️|stopwatch',
    '⌛|hourglass', '📡|antenna', '🔋|battery', '🔌|plug', '💡|bulb',
    '🔦|flashlight', '🕯️|candle', '🧯|extinguisher', '🛢️|oil drum',
    '💸|money wings', '💵|dollar', '💰|money bag', '💳|credit card',
    '💎|gem', '⚖️|scales', '🧰|toolbox', '🔧|wrench', '🔨|hammer',
    '⚒️|hammer pick', '🛠️|hammer wrench', '⛏️|pick', '🔩|nut and bolt',
    '⚙️|gear', '🧲|magnet', '🔫|water gun', '💣|bomb', '🧨|firecracker',
    '🪓|axe', '🔪|knife', '🗡️|dagger', '⚔️|swords', '🛡️|shield',
    '🚬|cigarette', '⚰️|coffin', '🏺|amphora', '🔮|crystal ball',
    '📿|beads', '🧿|nazar', '💈|barber', '⚗️|alembic', '🔭|telescope',
    '🔬|microscope', '🕳️|hole', '💊|pill', '💉|syringe', '🩹|bandaid',
    '🩺|stethoscope', '🌡️|thermometer tool', '🧬|dna', '🦠|microbe',
    '🧫|petri dish', '🧪|test tube', '🚪|door', '🛏️|bed', '🛋️|couch',
    '🪑|chair', '🚽|toilet', '🚿|shower', '🛁|bathtub', '🧴|lotion',
    '🧷|safety pin', '🧹|broom', '🧺|basket', '🧻|paper roll', '🧼|soap',
    '🪥|toothbrush', '🧽|sponge', '🛒|cart', '🎁|gift', '🎈|balloon',
    '🎏|carp streamer', '🎀|ribbon bow', '🎊|confetti ball', '🎉|party popper',
    '🪄|magic wand', '📦|package', '📫|mailbox', '✉️|envelope', '📜|scroll',
    '📃|page curl', '📑|bookmark tabs', '📊|bar chart', '📈|chart up',
    '📉|chart down', '📋|clipboard', '📌|pushpin', '📎|paperclip',
    '📏|ruler', '✂️|scissors', '🖊️|pen', '✏️|pencil', '🔍|magnifier',
    '🔒|lock', '🔓|unlock', '🔑|key', '🗝️|old key', '📚|books', '📖|book',
  ])),
  EmojiGroup('Symbols', '❤️', _parse(const [
    '❤️|red heart', '🧡|orange heart', '💛|yellow heart', '💚|green heart',
    '💙|blue heart', '💜|purple heart', '🖤|black heart', '🤍|white heart',
    '🤎|brown heart', '💔|broken heart', '❣️|heart exclamation',
    '💕|two hearts', '💞|revolving hearts', '💓|beating heart',
    '💗|growing heart', '💖|sparkling heart', '💘|heart arrow',
    '💝|heart ribbon', '💟|heart decoration', '☮️|peace', '✝️|cross',
    '☪️|star crescent', '🕉️|om', '☸️|dharma', '✡️|star of david',
    '☯️|yin yang', '⛎|ophiuchus', '♈|aries', '♉|taurus', '♊|gemini',
    '♋|cancer', '♌|leo', '♍|virgo', '♎|libra', '♏|scorpio',
    '♐|sagittarius', '♑|capricorn', '♒|aquarius', '♓|pisces', '🆔|id',
    '⚛️|atom', '☢️|radioactive', '☣️|biohazard', '📴|phone off',
    '📳|vibration', '🈶|not free', '🈚|free of charge', '🈸|application',
    '🈺|open for business', '🈷️|monthly', '✴️|eight pointed star',
    '🆚|vs', '💮|white flower', '🉐|bargain', '㊙️|secret', '㊗️|congrats',
    '🈴|passing grade', '🈵|no vacancy', '🔞|18 plus', '📵|no phones',
    '🚭|no smoking', '❗|exclamation', '❕|white exclamation', '❓|question',
    '❔|white question', '‼️|double exclamation', '⁉️|interrobang',
    '💯|hundred', '🔅|dim', '🔆|bright', '⚠️|warning', '🚸|children crossing',
    '🔱|trident', '⚜️|fleur de lis', '🔰|beginner', '♻️|recycle',
    '✅|check mark', '❌|cross mark', '❎|cross button', '🌐|globe',
    '💠|diamond dot', 'Ⓜ️|circled m', '🌀|cyclone', '💤|zzz', '🏧|atm',
    '🚾|wc', '♿|wheelchair symbol', '🅿️|parking', '🛗|elevator',
    '🈳|vacancy', '🈂️|service', '🛂|passport', '🛃|customs', '🛄|baggage',
    '🛅|left luggage', '🚹|mens', '🚺|womens', '🚼|baby symbol',
    '🚻|restroom', '🚮|litter', '🎦|cinema', '📶|signal', '🈁|here',
    '🔣|symbols', 'ℹ️|information', '🔤|abc', '🔡|abcd lower', '🔠|abcd upper',
    '🆖|ng', '🆗|ok button', '🆙|up button', '🆒|cool', '🆕|new', '🆓|free',
    '🔟|ten', '🔢|1234', '#️⃣|hash', '*️⃣|asterisk', '▶️|play', '⏸️|pause',
    '⏯️|play pause', '⏹️|stop', '⏺️|record', '⏭️|next track', '⏮️|prev track',
    '⏩|fast forward', '⏪|rewind', '🔀|shuffle', '🔁|repeat', '🔂|repeat one',
    '◀️|reverse', '🔼|up triangle', '🔽|down triangle', '➡️|right arrow',
    '⬅️|left arrow', '⬆️|up arrow', '⬇️|down arrow', '↗️|up right',
    '↘️|down right', '↙️|down left', '↖️|up left', '↕️|up down',
    '↔️|left right', '↩️|reply arrow', '↪️|forward arrow', '🔃|clockwise',
    '🔄|counterclockwise', '➕|plus', '➖|minus', '➗|divide', '✖️|multiply',
    '♾️|infinity', '💲|dollar sign', '💱|currency exchange', '™️|trademark',
    '©️|copyright', '®️|registered', '🔚|end', '🔙|back', '🔛|on',
    '🔝|top', '🔜|soon',
  ])),
];

/// Case-insensitive substring search over every group (emoji char included so
/// pasting an emoji finds itself). Empty query → empty result (the panel
/// shows the grouped view instead).
List<EmojiEntry> searchEmoji(String query) {
  final q = query.trim().toLowerCase();
  if (q.isEmpty) return const [];
  return [
    for (final g in emojiGroups)
      for (final e in g.entries)
        if (e.name.contains(q) || e.char == q) e,
  ];
}
