#!/usr/bin/env bash
set -euo pipefail

# Autonomous local live test for the published pinned onion-stream file path.
#
# It provisions a fresh four-node local mesh:
#   A, B    = anonymous receivers/app endpoints (both publish rendezvous ads)
#   M1, M2 = relay-capable rendezvous/middle relays
#
# Then it runs test/native/onion_stream_file_live_test.dart with
# VEIL_ONION_STREAM_CIRCUIT=published. This catches failures that unit-level
# synthetic tests cannot see: published rendezvous resolution, circuit splice,
# stream pull back to the sender, app-level offer/download/finalize, and rough
# throughput.
#
# Useful knobs:
#   ONION_STREAM_LIVE_BUILD=auto|0|1     build release native artifacts if needed
#   ONION_STREAM_LIVE_RUN_TEST=1|0       run Flutter test after nodes are ready
#   ONION_STREAM_LIVE_KEEP_NODES=0|1     leave nodes running after script exit
#   ONION_STREAM_LIVE_CHECK_LOGS=1|0     fail if node logs contain known bad markers
#   ONION_STREAM_LIVE_TEST_TIMEOUT=10m   flutter test timeout
#   ONION_STREAM_LIVE_REUSE_IDENTITIES=1 reuse mined local identities/configs
#   ONION_STREAM_LIVE_SEED_DIR=.dev-mailbox-onion
#                                      source identities for a/b/m1/m2
#   ONION_STREAM_LIVE_DART_DEFINES="K=V ..."
#                                      extra --dart-define values for flutter test
#   XVEIL_STREAM_RANGE_PARALLELISM=6     range-stream worker count dart-define
#   XVEIL_STREAM_RANGE_TARGET_BYTES=1048576
#                                      target contiguous bytes per range stream
#   XVEIL_TEST_FILE_SIZE=4194304         payload size generated by the test
#   XVEIL_TEST_MIN_MIB_PER_SEC=1.5       optional throughput floor

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VEIL="$ROOT/third_party/veil"
NODES="${ONION_STREAM_LIVE_NODES:-$ROOT/.dev-onion-stream}"
SEED_DIR="${ONION_STREAM_LIVE_SEED_DIR:-$ROOT/.dev-mailbox-onion}"
PROFILE="${ONION_STREAM_LIVE_PROFILE:-release}"
BUILD="${ONION_STREAM_LIVE_BUILD:-auto}"
RUN_TEST="${ONION_STREAM_LIVE_RUN_TEST:-1}"
KEEP_NODES="${ONION_STREAM_LIVE_KEEP_NODES:-0}"
CHECK_LOGS="${ONION_STREAM_LIVE_CHECK_LOGS:-1}"
TEST_TIMEOUT="${ONION_STREAM_LIVE_TEST_TIMEOUT:-10m}"
REUSE_IDENTITIES="${ONION_STREAM_LIVE_REUSE_IDENTITIES:-1}"
MINT_DIFFICULTY="${VEIL_MINT_DIFFICULTY:-24}"
LOG_LEVEL="${ONION_STREAM_LIVE_RUST_LOG:-info,veil_node_runtime=debug}"
DART_DEFINES=()

case "$(uname -s)" in
  Darwin) DYLIB_EXT="dylib" ;;
  Linux) DYLIB_EXT="so" ;;
  *) DYLIB_EXT="dll" ;;
esac

BIN="${VEIL_CLI:-$VEIL/target/$PROFILE/veil-cli}"
DYLIB="${VEIL_FFI_DYLIB:-$VEIL/target/$PROFILE/libveilclient_ffi.$DYLIB_EXT}"
peers=(a b m1 m2)
pids=()
flutter_pid=""
cleaned_up=0

if ! [[ "$MINT_DIFFICULTY" =~ ^[0-9]+$ ]] || (( MINT_DIFFICULTY < 24 )); then
  echo "VEIL_MINT_DIFFICULTY must be an integer >= 24 (node validation floor)." >&2
  exit 2
fi

maybe_build() {
  local need=0
  [[ -x "$BIN" ]] || need=1
  [[ -f "$DYLIB" ]] || need=1
  if [[ "$BUILD" == "auto" && "$need" == "0" ]]; then
    local newer
    newer="$(
      find \
        "$VEIL/Cargo.toml" \
        "$VEIL/Cargo.lock" \
        "$VEIL/crates/veil-cli" \
        "$VEIL/crates/veilclient-ffi" \
        "$VEIL/crates/veil-node-runtime" \
        "$VEIL/crates/veil-anonymity" \
        "$VEIL/crates/veil-onion-stream" \
        -type f \( -newer "$BIN" -o -newer "$DYLIB" \) \
        -print -quit 2>/dev/null || true
    )"
    if [[ -n "$newer" ]]; then
      need=1
    fi
  fi
  if [[ "$BUILD" == "1" || ( "$BUILD" == "auto" && "$need" == "1" ) ]]; then
    echo "==> building release veil-cli + node-embedded veilclient-ffi"
    (
      cd "$VEIL"
      cargo build --release -p veil-cli --features allow-empty-seeds
      cargo build --release -p veilclient-ffi --features node-embedded,allow-empty-seeds
    )
  fi
  [[ -x "$BIN" ]] || {
    echo "missing veil-cli: $BIN (set ONION_STREAM_LIVE_BUILD=1)" >&2
    exit 2
  }
  [[ -f "$DYLIB" ]] || {
    echo "missing veilclient ffi dylib: $DYLIB (set ONION_STREAM_LIVE_BUILD=1)" >&2
    exit 2
  }
}

mk_node() {
  local dir="$1"
  local port="$2"
  local name
  local seeded=0
  local cfg="$dir/config.toml"
  name="$(basename "$dir")"

  if [[ "$REUSE_IDENTITIES" == "1" ]]; then
    if copy_seed_node "$name" "$dir"; then
      seeded=1
    fi
  fi

  if [[ "$seeded" != "1" ]]; then
    rm -rf "$dir"
    mkdir -p "$dir"
    run_with_heartbeat "config init $name" \
      "$BIN" config init -f -d 0 "$cfg"
    run_with_heartbeat "mine nonce $name" \
      "$BIN" -c "$cfg" key nonce --difficulty "$MINT_DIFFICULTY"
  fi

  [[ -f "$cfg" ]] || {
    echo "config init failed for $dir" >&2
    exit 1
  }
  strip_local_runtime_blocks "$cfg"
  "$BIN" -c "$cfg" key info >/dev/null
  "$BIN" -c "$cfg" listen add "tcp://127.0.0.1:$port" >/dev/null 2>&1 || true
  "$BIN" -c "$cfg" config set global.admin_socket "unix://$dir/config.sock" >/dev/null 2>&1 || true
  "$BIN" -c "$cfg" config set ipc.enabled true >/dev/null 2>&1 || true
  "$BIN" -c "$cfg" config set ipc.socket_uri "unix://$dir/app.sock" >/dev/null 2>&1 || true
}

seed_path_for() {
  case "$1" in
    a) printf '%s\n' "$SEED_DIR/send" ;;
    b) printf '%s\n' "$SEED_DIR/fetch" ;;
    m1) printf '%s\n' "$SEED_DIR/mid1" ;;
    m2) printf '%s\n' "$SEED_DIR/mid2" ;;
    *) return 1 ;;
  esac
}

clean_node_runtime_files() {
  local dir="$1"
  rm -f \
    "$dir/admin-audit.log" \
    "$dir/app.sock" \
    "$dir/app.tmp" \
    "$dir/config.sock" \
    "$dir/dht_values.json" \
    "$dir/identity_document.bin" \
    "$dir/node.log" \
    "$dir/node.pid" \
    "$dir/peers_discovered.json" \
    2>/dev/null || true
  rm -rf "$dir/mailbox" 2>/dev/null || true
}

copy_seed_node() {
  local name="$1"
  local dir="$2"
  local src
  src="$(seed_path_for "$name")" || return 1
  [[ -f "$src/config.toml" ]] || return 1
  "$BIN" -c "$src/config.toml" key info >/dev/null 2>&1 || return 1

  rm -rf "$dir"
  mkdir -p "$dir"
  cp -R "$src/." "$dir/"
  clean_node_runtime_files "$dir"
  echo "   reuse seeded identity $name <- $src"
}

run_with_heartbeat() {
  local label="$1"
  shift
  echo "   $label..."
  "$@" >/dev/null 2>&1 &
  local pid="$!"
  while kill -0 "$pid" 2>/dev/null; do
    sleep 10
    if kill -0 "$pid" 2>/dev/null; then
      echo "   $label still running..."
    fi
  done
  wait "$pid"
}

add_dart_define() {
  DART_DEFINES+=(--dart-define="$1")
}

collect_dart_defines() {
  local item
  if [[ -n "${ONION_STREAM_LIVE_DART_DEFINES:-}" ]]; then
    for item in $ONION_STREAM_LIVE_DART_DEFINES; do
      [[ -n "$item" ]] && add_dart_define "$item"
    done
  fi
  if [[ -n "${XVEIL_STREAM_RANGE_PARALLELISM:-}" ]]; then
    add_dart_define "XVEIL_STREAM_RANGE_PARALLELISM=$XVEIL_STREAM_RANGE_PARALLELISM"
  fi
  if [[ -n "${XVEIL_STREAM_RANGE_TARGET_BYTES:-}" ]]; then
    add_dart_define "XVEIL_STREAM_RANGE_TARGET_BYTES=$XVEIL_STREAM_RANGE_TARGET_BYTES"
  fi
}

invite_of() {
  "$BIN" -c "$1/config.toml" bootstrap invite 2>/dev/null |
    grep -oE 'veil:bootstrap\S+' |
    head -1
}

node_id_of() {
  "$BIN" -c "$1/config.toml" key info 2>/dev/null |
    awk '/^node_id:/ { print $2; exit }'
}

strip_anonymity_block() {
  local cfg="$1"
  local tmp="$cfg.tmp"
  awk '
    /^\[anonymity\][[:space:]]*$/ { skip = 1; next }
    /^\[[^]]+\][[:space:]]*$/ { skip = 0 }
    !skip { print }
  ' "$cfg" >"$tmp"
  mv "$tmp" "$cfg"
}

strip_local_runtime_blocks() {
  local cfg="$1"
  local tmp="$cfg.tmp"
  awk '
    /^\[\[listen\]\][[:space:]]*$/ { skip = 1; next }
    /^\[\[bootstrap_peers\]\][[:space:]]*$/ { skip = 1; next }
    /^\[anonymity\][[:space:]]*$/ { skip = 1; next }
    /^\[\[[^]]+\]\][[:space:]]*$/ { skip = 0 }
    /^\[[^]]+\][[:space:]]*$/ { skip = 0 }
    !skip { print }
  ' "$cfg" >"$tmp"
  mv "$tmp" "$cfg"
}

tail_node_logs() {
  for n in "${peers[@]}"; do
    echo "===== $n"
    tail -80 "$NODES/$n/node.log" 2>/dev/null || true
  done
}

check_node_logs() {
  [[ "$CHECK_LOGS" == "1" ]] || return 0

  local pattern
  pattern='DHT quota|auto_ban|rate_limited|session\.violation|piece failed|truncated'

  local hits=0
  for n in "${peers[@]}"; do
    local log="$NODES/$n/node.log"
    [[ -f "$log" ]] || continue
    if grep -EIn "$pattern" "$log" >&2; then
      hits=1
    fi
  done

  if [[ "$hits" == "1" ]]; then
    echo "node logs contain known onion-stream failure markers" >&2
    return 1
  fi
}

nodes_alive() {
  local pid
  for pid in "${pids[@]:-}"; do
    kill -0 "$pid" 2>/dev/null || return 1
  done
}

rendezvous_registered() {
  local log="$1"
  grep -Eqs \
    '(anonymity\.rendezvous_recipient\.(registered|refreshed|event_driven_reregister).*registered with [0-9]+ rendezvous relays?|registered with rendezvous relay)' \
    "$log"
}

stop_existing_nodes() {
  local pid pid_file old_pids
  for pid_file in "$NODES"/*/node.pid; do
    [[ -f "$pid_file" ]] || continue
    pid="$(cat "$pid_file" 2>/dev/null || true)"
    [[ -n "$pid" ]] || continue
    kill "$pid" 2>/dev/null || true
  done

  old_pids="$(pgrep -f "$NODES/.*/config.toml" 2>/dev/null || true)"
  [[ -n "$old_pids" ]] || return 0
  echo "==> stopping stale local onion-stream nodes"
  while read -r pid; do
    [[ -n "$pid" ]] || continue
    kill "$pid" 2>/dev/null || true
  done <<<"$old_pids"
  sleep 2
  while read -r pid; do
    [[ -n "$pid" ]] || continue
    kill -9 "$pid" 2>/dev/null || true
  done <<<"$old_pids"
}

stop_existing_live_harnesses() {
  local old_pids pid cmd
  old_pids="$(pgrep -f 'scripts/onion-stream-local-live\.sh' 2>/dev/null || true)"
  [[ -n "$old_pids" ]] || return 0
  while read -r pid; do
    [[ -n "$pid" ]] || continue
    [[ "$pid" == "$$" || "$pid" == "$BASHPID" || "$pid" == "$PPID" ]] && continue
    cmd="$(ps -p "$pid" -o command= 2>/dev/null || true)"
    [[ "$cmd" == *"scripts/onion-stream-local-live.sh"* ]] || continue
    echo "==> stopping stale onion-stream live harness pid $pid"
    kill "$pid" 2>/dev/null || true
  done <<<"$old_pids"
}

stop_existing_flutter_tests() {
  local old_pids
  old_pids="$(
    pgrep -f 'flutter_tools\.snapshot test .*onion_stream_file_live_test\.dart|flutter_tester.*flutter_test_listener' \
      2>/dev/null || true
  )"
  [[ -n "$old_pids" ]] || return 0
  echo "==> stopping stale onion-stream live Flutter tests"
  while read -r pid; do
    [[ -n "$pid" ]] || continue
    kill "$pid" 2>/dev/null || true
  done <<<"$old_pids"
  sleep 2
  while read -r pid; do
    [[ -n "$pid" ]] || continue
    kill -0 "$pid" 2>/dev/null || continue
    kill -9 "$pid" 2>/dev/null || true
  done <<<"$old_pids"
}

cleanup() {
  local code=$?
  if [[ "$cleaned_up" == "1" ]]; then
    exit "$code"
  fi
  cleaned_up=1
  if [[ -n "${flutter_pid:-}" ]]; then
    kill "$flutter_pid" 2>/dev/null || true
  fi
  stop_existing_flutter_tests
  if [[ "$KEEP_NODES" != "1" ]]; then
    for pid in "${pids[@]:-}"; do
      kill "$pid" 2>/dev/null || true
    done
    for pid_file in "$NODES"/*/node.pid; do
      [[ -f "$pid_file" ]] || continue
      local pid
      pid="$(cat "$pid_file")"
      if kill -0 "$pid" 2>/dev/null; then
        kill "$pid" 2>/dev/null || true
      fi
    done
    sleep 1
    stop_existing_nodes
    wait 2>/dev/null || true
  fi
  echo "logs: $NODES/{a,b,m1,m2}/node.log"
  exit "$code"
}
trap cleanup EXIT INT TERM

stop_existing_live_harnesses
stop_existing_flutter_tests
maybe_build
collect_dart_defines
stop_existing_nodes

echo "==> provisioning local onion-stream mesh (difficulty $MINT_DIFFICULTY)"
mk_node "$NODES/a" 9230
mk_node "$NODES/b" 9231
mk_node "$NODES/m1" 9232
mk_node "$NODES/m2" 9233

echo "==> peering local mesh"
for a in "${peers[@]}"; do
  for b in "${peers[@]}"; do
    [[ "$a" == "$b" ]] && continue
    "$BIN" -c "$NODES/$a/config.toml" bootstrap join \
      --uri "$(invite_of "$NODES/$b")" >/dev/null 2>&1 || true
  done
done

echo "==> enabling anonymity roles"
for n in "${peers[@]}"; do
  strip_anonymity_block "$NODES/$n/config.toml"
done
relay_m1="$(node_id_of "$NODES/m1")"
relay_m2="$(node_id_of "$NODES/m2")"
[[ -n "$relay_m1" && -n "$relay_m2" ]] || {
  echo "failed to read m1/m2 node ids for rendezvous pinning" >&2
  exit 1
}
printf '\n[anonymity]\nreceive_anonymous = true\nonion_service = true\nrendezvous_relays = ["%s", "%s"]\n' "$relay_m1" "$relay_m2" >>"$NODES/a/config.toml"
printf '\n[anonymity]\nreceive_anonymous = true\nonion_service = true\nrendezvous_relays = ["%s", "%s"]\n' "$relay_m1" "$relay_m2" >>"$NODES/b/config.toml"
printf '\n[anonymity]\nrelay_capable = true\n' >>"$NODES/m1/config.toml"
printf '\n[anonymity]\nrelay_capable = true\n' >>"$NODES/m2/config.toml"

stop_existing_nodes
rm -f "$NODES"/*/dht_values.json "$NODES"/*/app.sock "$NODES"/*/app.tmp \
  "$NODES"/*/config.sock "$NODES"/*/node.pid 2>/dev/null || true

echo "==> starting nodes"
for n in "${peers[@]}"; do
  (
    cd "$ROOT"
    RUST_LOG="$LOG_LEVEL" "$BIN" -c "$NODES/$n/config.toml" node run --foreground
  ) >"$NODES/$n/node.log" 2>&1 &
  pid="$!"
  echo "$pid" >"$NODES/$n/node.pid"
  pids+=("$pid")
done

echo "==> waiting for app sockets"
for i in $(seq 1 90); do
  if [[ -S "$NODES/a/app.sock" && -S "$NODES/b/app.sock" ]]; then
    break
  fi
  if ! nodes_alive; then
    echo "one or more nodes exited before app sockets appeared" >&2
    tail_node_logs >&2
    exit 1
  fi
  if (( i % 10 == 0 )); then
    echo "   still waiting for app sockets (${i}s)"
  fi
  sleep 1
done
[[ -S "$NODES/a/app.sock" && -S "$NODES/b/app.sock" ]] || {
  echo "nodes failed to expose app sockets" >&2
  tail_node_logs >&2
  exit 1
}

echo "==> waiting for A and B rendezvous registrations"
registered=0
for i in $(seq 1 180); do
  if rendezvous_registered "$NODES/a/node.log" &&
    rendezvous_registered "$NODES/b/node.log"; then
    registered=1
    break
  fi
  if ! nodes_alive; then
    echo "one or more nodes exited before rendezvous registration" >&2
    tail_node_logs >&2
    exit 1
  fi
  if (( i % 10 == 0 )); then
    echo "   still waiting for rendezvous registration (${i}s)"
  fi
  sleep 1
done
if [[ "$registered" != "1" ]]; then
  echo "A/B did not both register rendezvous relays within 180s" >&2
  tail_node_logs >&2
  exit 1
fi
echo "==> rendezvous ready"

if [[ "$RUN_TEST" == "1" ]]; then
  echo "==> running live file transfer"
  test_code=0
  test_log="$NODES/flutter-test.log"
  rm -f "$test_log"
  set +e
  (
    cd "$ROOT"
    VEIL_FFI_DYLIB="$DYLIB" \
      VEIL_ONION_STREAM_CIRCUIT=published \
      XVEIL_TEST_SOCK_A="$NODES/a/app.sock" \
      XVEIL_TEST_SOCK_B="$NODES/b/app.sock" \
      flutter test --timeout="$TEST_TIMEOUT" "${DART_DEFINES[@]}" \
        test/native/onion_stream_file_live_test.dart
  ) > >(tee "$test_log") 2>&1 &
  flutter_pid="$!"
  wait "$flutter_pid"
  test_code=$?
  flutter_pid=""
  set -e
  if grep -Eiq 'Some tests failed|No tests were found|did not complete|TestDeviceException|Bad state: Cannot (close sink|add event)|uncaught errors occurred shutting down|Failing tests:' "$test_log"; then
    test_code=1
  fi
  check_node_logs || {
    tail_node_logs >&2
    exit 1
  }
  exit "$test_code"
else
  cat <<EOF

Mesh is running.

Run:
  VEIL_FFI_DYLIB="$DYLIB" \\
  VEIL_ONION_STREAM_CIRCUIT=published \\
  XVEIL_TEST_SOCK_A="$NODES/a/app.sock" \\
  XVEIL_TEST_SOCK_B="$NODES/b/app.sock" \\
  flutter test test/native/onion_stream_file_live_test.dart

EOF
fi
